 GET  http://localhost:5168/todo/

###

 GET  http://localhost:5168/todo?id=1

#  {
#     "id":"2"
#  }

 ###

POST  http://localhost:5168/todo

{
    "id":1,
    "name": "create sub cat",
    "dueDate": "2024-12-12",
    "isCompleted":false,
}

###

 DELETE   http://localhost:5168/todo?id=2

#  {
#     "id":1
#  }

###

GET  http://localhost:5168/tasks/